name: additive_food
description: Additive food.

version: 1.0.0+1

environment:
  sdk: "^2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  built_value:
  built_collection:
  flutter_redux:
  redux_thunk:
  redux_logging:
  flutter_redux_navigation:
  cupertino_icons:
  flutter_svg: 0.11.0
  rxdart:
  http:
  get_it:
  camera:
  firebase_core:
  firebase_auth:
  google_sign_in:
  firebase_analytics:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  built_value_generator: ^6.1.4
  intl_translation: ^0.17.1

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
fonts:
  - family: Raleway
    fonts:
      - asset: fonts/main.otf
