name: additive_food
description: Additive food.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_value:
  built_collection:
  flutter_redux:
  redux_thunk:
  redux_logging:
  flutter_redux_navigation:
  cupertino_icons:
  flutter_svg:
  rxdart:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  built_value_generator: ^6.1.4

flutter:
  uses-material-design: true
  assets:
  - assets/images/