[versions]
dagger = "2.40.1"
hiltLifecycle = "1.0.0"
jumio = "3.9.2"
lifecycle = "2.4.0"
kotlin = "1.5.31"
kotlinCoroutines = "1.5.1"
kotlinSerialization = "1.2.2"
dataStore = "1.0.0"
compose = "1.0.5"
accompanist = "0.20.0"
coil = "1.3.2"
papercut = "0.9.1"
protobuf = "3.14.0"
navigation = "2.3.5"
splashscreen = "1.0.0-alpha02"

[libraries]
androidx-paging = "androidx.paging:paging-runtime:3.0.1"
androidx-core = "androidx.core:core-ktx:1.5.0"
androidx-activity = "androidx.activity:activity-ktx:1.3.1"
androidx-appcompat = "androidx.appcompat:appcompat:1.3.1"
androidx-cardview = "androidx.cardview:cardview:1.0.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.0.4"
androidx-fragment = "androidx.fragment:fragment-ktx:1.3.6"
androidx-viewpager2 = "androidx.viewpager2:viewpager2:1.0.0"
androidx-viewpager = "androidx.viewpager:viewpager:1.0.0"
androidx-flexbox = "com.google.android.flexbox:flexbox:3.0.0"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
androidx-customtabs = { module = "androidx.browser:browser", version = "1.2.0" }
androidx-transitions = "androidx.transition:transition:1.4.1"
androidx-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
androidx-dynamicanimation = "androidx.dynamicanimation:dynamicanimation:1.0.0"
androidx-work = "androidx.work:work-runtime-ktx:2.7.0-rc01"
androidx-room = "androidx.room:room-runtime:2.3.0"
androidx-navigation-fragment =  { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui =  { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
material-components = "com.google.android.material:material:1.4.0"

android-install-referrer = "com.android.installreferrer:installreferrer:2.2"
easypermission = "pub.devrel:easypermissions:3.0.0"
fotoApparat = "io.fotoapparat:fotoapparat:2.7.0"
mapUtils = "com.google.maps.android:android-maps-utils:2.2.6"
gson = "com.google.code.gson:gson:2.8.6"
lottie = "com.airbnb.android:lottie:3.4.4"
pinView = "io.github.chaosleung:pinview:1.4.4"
stripe = "com.stripe:stripe-android:16.1.1"
timber = "com.jakewharton.timber:timber:4.7.1"
viewPagerIndicator = "com.github.romandanylyk:PageIndicatorView:b1bad589b5"
zendesk = "com.zendesk:support:5.0.2"

papercut-core = { module = "ie.stu:papercut-annotations", version.ref = "papercut" }
papercut-compiler = { module = "ie.stu:papercut-compiler", version.ref = "papercut" }

protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf"}
protobuf-compiler = { module = "com.google.protobuf:protoc", version.ref = "protobuf"}

dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }
hilt-android-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltLifecycle" }
hilt-android-core = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-android-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltLifecycle" }
hilt-compiler-core = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
jumio-netverify-barcode = { module = "com.jumio.android:nv-barcode", version.ref = "jumio" }
jumio-core = { module = "com.jumio.android:core", version.ref = "jumio" }
jumio-iproov = { module = "com.jumio.android:iproov", version.ref = "jumio" }
iproov = "com.iproov.sdk:iproov:6.5.1"
netverify-core = { module = "com.jumio.android:nv", version.ref = "jumio" }
netverify-mrz = { module = "com.jumio.android:nv-mrz", version.ref = "jumio" }
netverify-ocr = { module = "com.jumio.android:nv-ocr", version.ref = "jumio" }
leanplum-core = "com.leanplum:leanplum-core:5.6.1"
leanplum-fcm = "com.leanplum:leanplum-fcm:5.6.1"
adyen3ds2 = "com.adyen.threeds:adyen-3ds2:2.2.4"
processOut = "com.github.processout:processout-android:2.14.0"
adjust = "com.adjust.sdk:adjust-android:4.28.5"
# Can be removed when https://github.com/processout/processout-android/issues/22 is done
volley = "com.android.volley:volley:1.2.1"

play-services-core = "com.google.android.play:core-ktx:1.8.1"
play-services-auth = "com.google.android.gms:play-services-auth:19.2.0"
play-services-location = "com.google.android.gms:play-services-location:18.0.0"
play-services-maps = "com.google.android.gms:play-services-maps:18.0.0"

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }

androidx-datastore-proto = { module = "androidx.datastore:datastore", version.ref = "dataStore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinSerialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }

coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

firebase-analytics = "com.google.firebase:firebase-analytics:19.0.1"
firebase-auth = "com.google.firebase:firebase-auth:21.0.1"
firebase-messaging = "com.google.firebase:firebase-messaging:22.0.0"
firebase-iid = "com.google.firebase:firebase-iid:21.1.0"
firebase-storage = "com.google.firebase:firebase-storage:20.0.0"
firebase-crashlytics = "com.google.firebase:firebase-crashlytics:18.2.1"
firebase-dynamicLinks = "com.google.firebase:firebase-dynamic-links:20.1.1"
firebase-firestore = "com.google.firebase:firebase-firestore:23.0.3"
firebase-functions = "com.google.firebase:firebase-functions:20.0.1"
firebase-performance = "com.google.firebase:firebase-perf:20.0.2"
firebase-vision = "com.google.firebase:firebase-ml-vision:24.0.3"

androidx-compose-activity = "androidx.activity:activity-compose:1.3.1"
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-compose-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material-core = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
androidx-compose-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
androidx-compose-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
androidx-compose-lifecycle = "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha07"
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
rider-analytics = "com.ridedott.rider:analytics-ktx:1.10.0"
rider-api = "com.ridedott.rider:rider-android-ktx:1.1.65"

[bundles]
compose = [
    "androidx-compose-activity",
    "androidx-compose-compiler",
    "androidx-compose-runtime",
    "androidx-compose-ui",
    "androidx-compose-livedata",
    "androidx-compose-tooling",
    "androidx-compose-foundation",
    "androidx-compose-material-core",
    "androidx-compose-insets",
    "androidx-compose-flowlayout",
    "androidx-compose-lifecycle",
    "androidx-compose-permissions",
]
ui = [
    "androidx-paging",
    "androidx-activity",
    "androidx-appcompat",
    "androidx-cardview",
    "androidx-constraintlayout",
    "androidx-fragment",
    "androidx-viewpager",
    "androidx-viewpager2",
    "androidx-flexbox",
    "androidx-recyclerview",
    "androidx-customtabs",
    "androidx-transitions",
    "androidx-savedstate",
    "material-components"
]
di = [
    "dagger-core",
    "hilt-android-core",
    "hilt-android-work"
]
coil = [
    "coil-core",
    "coil-compose",
]
diCompiler = [
    "dagger-compiler",
    "hilt-android-compiler",
    "hilt-compiler-core"
]
lifecycle = [
    "androidx-lifecycle-runtime",
    "androidx-lifecycle-livedata",
    "androidx-lifecycle-viewmodel",
    "androidx-lifecycle-common",
    "androidx-lifecycle-process"
]
kotlin = [
    "kotlin-stdlib",
    "kotlin-coroutines-core",
    "kotlin-coroutines-android",
]
navigation = [
    "androidx-navigation-fragment",
    "androidx-navigation-ui"
]
kotlinSerialization = [
    "kotlin-serialization-core",
    "kotlin-serialization-json",
]
jumio = [
    "jumio-netverify-barcode",
    "jumio-core",
    "jumio-iproov",
    "netverify-core",
    "netverify-mrz",
    "netverify-ocr"
]
