[versions]
dagger = "2.40.1"
hiltLifecycle = "1.0.0"
jumio = "3.9.2"
lifecycle = "2.4.0"
kotlin = "1.5.31"
kotlinCoroutines = "1.5.1"
kotlinSerialization = "1.2.2"
dataStore = "1.0.0"
compose = "1.0.5"
accompanist = "0.20.0"
coil = "1.3.2"
papercut = "0.9.1"
protobuf = "3.14.0"
navigation = "2.3.5"
splashscreen = "1.0.0-alpha02"

[libraries]
androidx-paging = "androidx.paging:paging-runtime:3.0.1"
androidx-core = "androidx.core:core-ktx:1.5.0"
androidx-activity = "androidx.activity:activity-ktx:1.3.1"
androidx-appcompat = "androidx.appcompat:appcompat:1.3.1"
androidx-cardview = "androidx.cardview:cardview:1.0.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.0.4"
androidx-fragment = "androidx.fragment:fragment-ktx:1.3.6"
androidx-viewpager2 = "androidx.viewpager2:viewpager2:1.0.0"
androidx-viewpager = "androidx.viewpager:viewpager:1.0.0"
androidx-flexbox = "com.google.android.flexbox:flexbox:3.0.0"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
androidx-customtabs = { module = "androidx.browser:browser", version = "1.2.0"  }
androidx-transitions = "androidx.transition:transition:1.4.1"
androidx-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
androidx-dynamicanimation = "androidx.dynamicanimation:dynamicanimation:1.0.0"
androidx-work = "androidx.work:work-runtime-ktx:2.7.0-rc01"
androidx-room = "androidx.room:room-runtime:2.3.0"